### PR TITLE
feat: add support for launching on Windows platform

### PR DESCRIPTION
**Pull request by Hintay**
This is an initial patch that ensures Nginx UI can launch on Windows platform.
‼️Full functionality on Windows is not guaranteed.

### CODE REVIEW

**Review by 0xJacky — APPROVED** [review]

**Comment by Hintay** [comment]
We should test compatibility for Docker.

**Comment by 0xJacky** [comment]
Bug: OTA upgrades to this version(risefront) from previous verison(oversee) can not auto restart.

image

**Comment by zgcwkj** [comment]
Test results: Unable to initialize the database under Windows system

**Comment by 0xJacky** [comment]
Hi @zgcwkj, Did you compile Nginx UI on Windows? You need to enable CGO.

**Comment by zgcwkj** [comment]
> Hi @zgcwkj, Did you compile Nginx UI on Windows? You need to enable CGO.

Thank you, after configuring correctly, the compiled version can run normally.
**Notes:**
```
sudo apt-get install mingw-w64
export CC=x86_64-w64-mingw32-gcc

export CGO_ENABLED=1
export GOOS=windows
export GOARCH=amd64

go build -ldflags="-w -s" -trimpath
```

**Comment by 0xJacky** [comment]
> > Hi @zgcwkj, Did you compile Nginx UI on Windows? You need to enable CGO.
> 
> Thank you, after configuring correctly, the compiled version can run normally. **Notes:**
> 
> ```
> sudo apt-get install mingw-w64
> export CC=x86_64-w64-mingw32-gcc
> 
> export CGO_ENABLED=1
> export GOOS=windows
> export GOARCH=amd64
> 
> go build -ldflags="-w -s" -trimpath
> ```

That's right. Additionally, if someone wants to compile Nginx UI for Windows on macOS, you can install `mingw-w64` via
```
brew install mingw-w64
```

then compile it.
```
CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ GOOS=windows GOARCH=amd64 go build main.go
```

https://github.com/0xJacky/nginx-ui/issues/9

**Comment by jxs1211** [comment]
> > Hi @zgcwkj, Did you compile Nginx UI on Windows? You need to enable CGO.
> 
> Thank you, after configuring correctly, the compiled version can run normally. **Notes:**
> 
> ```
> sudo apt-get install mingw-w64
> export CC=x86_64-w64-mingw32-gcc
> 
> export CGO_ENABLED=1
> export GOOS=windows
> export GOARCH=amd64
> 
> go build -ldflags="-w -s" -trimpath
> ```

Hi, I try to run it on windows by following the step above, but can't booting up normally, what did I miss?
```
➜  nginx-ui git:(dev) ✗ sudo apt-get install mingw-w64
export CC=x86_64-w64-mingw32-gcc

export CGO_ENABLED=1
export GOOS=windows
export GOARCH=amd64

go build -ldflags="-w -s" -trimpath -o nginx-ui.exe
```
bootup on windows terminal:
```sh
PS C:\Users\shen> .\nginx-ui.exe -config .\app.example.ini
2024/11/16 14:30:36 [overseer] disabled. run failed: Failed to retreive fd for: :9000 (file tcp [::]:9000: not supported by windows)
2024-11-16 14:30:36     INFO    github.com/0xJacky/Nginx-UI/main.go:41  Server exited
PS C:\Users\shen>
```

**Comment by Hintay** [comment]
Hi @jxs1211, by the way you can test the Windows version by checking out the [feat/platform-windows](https://github.com/0xJacky/nginx-ui/tree/feat/platform-windows) branch.

**Pull request merged**
