### PR TITLE
Adding French translation

### PR DESCRIPTION
**Pull request by skrilax91**
Adding French translation to the project.

### CODE REVIEW

**Comment by skrilax91** [comment]
I translated all sentences that I was able to solve, the last sentences were ambiguous.
Also, I don't know but I have the impression that the English translation is incorrectly translated

**Comment by Hintay** [comment]
Thank you for your contribution to the translation! We appreciate your effort in helping us make our project accessible to more people.

As non-native English speakers ourselves, we understand that translations can sometimes be challenging, and we appreciate the work you have done so far. If there are specific areas where you believe the English translation is incorrect, we would be grateful if you could point them out to us, as we are always looking to improve our project.

**Comment by skrilax91** [comment]
I finally tried to compile translations but the command `yarn gettext:compile` don't compile the new language

**Comment by 0xJacky** [comment]
> I finally tried to compile translations but the command `yarn gettext:compile` don't compile the new language

Thanks for your contributions, and you have to add the language code in this file `frontend/gettext.config.js` then you can use the `yarn gettext:extract` and `yarn gettext:compile` to extract or compile the translations.

**Comment by 0xJacky** [comment]
Thank you

**Pull request merged**
