### PR TITLE
Bugfix/Correct stream conf

### LINKED ISSUE #444: Unnecessary trailing `.conf` in default nginx stream configuration file
**Describe the bug**
There's an trailing `.conf` in default nginx stream configuration file.
That unnecessary suffix leads to the bug that nginx doesn't read conf generated from UI.

**To Reproduce**
1. Go to 'Manage Streams'
2. Click on 'Add.'
3. Create an configuration and enable it.

   ```conf
   server {
      listen 443;
   }
   ```

4. Attach to docker container and check the opened ports.
5. Observe that the port isn't listened as the config file UI generated file has no `.conf` suffix and do not read by nginx.
6. Change the name and add `.conf` suffix. Everything in stream works out of box.

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server: Docker
 - Nginx UI Version:  2.0.0-beta.26
 - Your Browser: Firefox

**Additional context**
`.conf` suffix should be deleted in nginx conf, similar as `site-enabled/*`

### PR DESCRIPTION
**Pull request by PeterWang-dev**
Fix #444

### CODE REVIEW

**Review by 0xJacky — APPROVED** [review]

**Comment by 0xJacky** [comment]
Thanks for your contribution. 🎉

**Comment by PeterWang-dev** [comment]
@0xJacky By the way, maybe you should announce user to update there `nginx.conf` as it is only generated on first run.

**Comment by PeterWang-dev** [comment]
I think maybe hide `nginx.conf` and boundle it with Docker image is more reasonable, that is, seperate nginx-ui generated config with nginx innner conf and adapt `nginx.conf` to read the files.

**Comment by PeterWang-dev** [comment]
> I think maybe hide `nginx.conf` and boundle it with Docker image is more reasonable, that is, seperate nginx-ui generated config with nginx innner conf and adapt `nginx.conf` to read the files.

However that may bring defects for those hardened user wanna customize nginx. That's a trade-off of design. Up to you.

**Comment by 0xJacky** [comment]
We’re planning to introduce a validator for nginx.conf to tackle these issues.

Forcing an override of nginx.conf can be very disruptive. Using a combination of a validator and a fixer might make the migration process much smoother.

https://github.com/users/0xJacky/projects/1/views/1?pane=issue&itemId=27245100

**Comment by PeterWang-dev** [comment]
> We’re planning to introduce a validator for nginx.conf to tackle these issues.
> 
> Forcing an override of nginx.conf can be very disruptive. Using a combination of a validator and a fixer might make the migration process much smoother.
> 
> https://github.com/users/0xJacky/projects/1/views/1?pane=issue&itemId=27245100

Got it. Thanks for your awsome work.

**Pull request merged**
